---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mas-core-deploy
  namespace: default
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: namespace
      type: string
      default: "masauto-operator-system"
    - name: operatorGroup
      type: string
      default: "masauto-operator-system-operator-group"
  tasks:
    - name: add-namespace
      TaskRef:
        kind: Task
        name: ibm-pak
      params:
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            kind: Namespace
            apiVersion: v1
            metadata:
              name: $(params.namespace)
            EOF
    - name: add-operator-group
      taskRef:
        kind: Task
        name: ibm-pak
      runAfter:
        - add-namespace
      params:
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              name: $(params.operatorGroup)
              namespace: $(params.namespace)
            spec:
              targetNamespaces:
                - $(params.namespace)
            EOF
    - name: get-ibm-entitlement-key
      taskRef:
        name: ibmcloud-secrets-manager-get
        kind: Task
      params:
        - name: KEY_ID
          value: 968d7819-f2c5-7b67-c420-3c6bfd51521e
        - name: SECRETS_MANAGER_ENDPOINT_URL
          value: >-
            https://afa20521-cd75-4864-843f-e59fd0ffd49d.us-south.secrets-manager.appdomain.cloud
    - name: add-entitlement-key
      taskRef:
        kind: Task
        name: ibm-pak
      runAfter:
        - get-ibm-entitlement-key
      params:
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            kind: Secret
            apiVersion: v1
            metadata:
              name: ibm-entitlement-key
              namespace: $(params.namespace)
            type: Opaque
            stringData:
              password: $(tasks.get-ibm-entitlement-key.results.secret-value)
              username: "cp"
            EOF
            sleep 10
    - name: fetch-repository
      taskRef:
        resolver: hub
        params:
          - name: kind
            value: task
          - name: name
            value: git-clone
          - name: version
            value: "0.9"
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/cloud-native-toolkit/operator-masauto"
        - name: revision
          value: "main"
    - name: add-catalog-source
      taskRef:
        kind: Task
        name: ibm-pak
      runAfter:
        - add-entitlement-key
      params:
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            apiVersion: operators.coreos.com/v1alpha1
            kind: CatalogSource
            metadata:
              name: ecosystem-engineering-catalog
              namespace: openshift-marketplace
              labels:
                app.kubernetes.io/name: ecosystem-engineering-catalog
                app.kubernetes.io/instance: ecosystem-engineering-catalog
                app.kubernetes.io/version: v0.16.0
            spec:
              displayName: ecosystem-engineering-catalog
              publisher: IBM
              sourceType: grpc
              image: quay.io/cloudnativetoolkit/ecosysengineer-catalog:latest
              updateStrategy:
                registryPoll:
                  interval: 90m
            EOF
            sleep 10
    - name: add-operator
      taskRef:
        kind: Task
        name: ibm-pak
      runAfter:
        - add-catalog-source
        - add-operator-group
      params:
        - name: SCRIPT
          value: |
            oc apply -f - <<EOF
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              name: masauto-operator
              namespace: $(params.namespace)
              labels:
                app.kubernetes.io/name: masauto-operator
                app.kubernetes.io/instance: masauto-operator
                app.kubernetes.io/version: "1.16.0"
            spec:
              channel: alpha
              installPlanApproval: Automatic
              name: masauto-operator
              source: ecosystem-engineering-catalog
              sourceNamespace: openshift-marketplace
            EOF
            sleep 20
    - name: add-mas-core
      taskRef:
        resolver: hub
        params:
          - name: name
            value: helm-upgrade-from-source
          - name: version
            value: "0.3"
      runAfter:
        - fetch-repository
        - add-operator
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: charts_dir
          value: charts/mas-core
        - name: values_file
          value: ../values_mas_core.yaml
    - name: wait-till-job-complete
      taskRef:
        kind: Task
        name: ibm-pak
      runAfter:
        - add-mas-core
      params:
        - name: SCRIPT
          value: |
            oc config current-context
            date
            oc wait --for=condition=available deployment/masauto-operator-controller-manager -n masauto-operator-system


