---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: pr-mas-deploy-
  namespace: default
spec:
  params:
    - name: uds-email
      value: "dev-techzone@ibm.com"
    - name: uds-firstname
      value: "TechZone"
    - name: uds-lastname
      value: "Developer"

    # install MAS Core. This task may be skipped once done successfully
    - name: mas-install-core
      value: "true"

    # install MAS Manage, depending on MAS Core
    - name: mas-install-cp4d-manage
      value: "false"
    - name: mas-cp4d-install-cognos
      value: "false"

    # install MAS IoT and Monitor, depending on MAS Core
    - name: mas-install-iot
      value: "false"
    - name: mas-install-monitor
      value: "false"

    # install MAS Predict, depending on MAS Core, Manage, IoT and Monitor
    - name: mas-install-predict
      value: "false"
    - name: cpd-platform-components
      value: "true"
    - name: cpd-install-spss
      value: "true"
    - name: cpd-wsl-projectname
      value: "maspredictproject"
    - name: cpd-wml-url
      value: "xxx"
    - name: cpd-admin-url
      value: "xxx"
    - name: cpd-admin-username
      value: "admin"
    - name: cpd-admin-password
      value: "xxx"

    # install MAS Predict, depending on MAS Core, Manage, IoT and Monitor
    - name: mas-install-aibroker
      value: "false"
    - name: watsonxai_apikey
      value: "Kpmlk3g41arip3HikRWySLzGj_CxOFZ18BiLLXsO-x68"
    - name: watsonxai_url
      value: "https://us-south.ml.cloud.ibm.com"
    - name: watsonxai_project_id
      value: "beb9043b-2d70-4eb7-9b07-fe9b6dde606e"
    - name: mas_aibroker_channel
      value: "9.0.x"

  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: "0"
    tasks: "24h"
  pipelineRef:
    name: mas-devops-deploy