---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-mas-cli-
spec:
  params:
    - name: uds-email
      value: "dev-techzone@ibm.com"
    - name: uds-firstname
      value: "TechZone"
    - name: uds-lastname
      value: "Developer"
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  pipelineRef:
    name: mas-cli-deploy
  podTemplate:
    securityContext:
      fsGroup: 65532
