---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pr-mas-devops-
spec:
  workspaces:
    - name: ws
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteMany
          resources:
            requests:
              storage: 1Gi
  timeouts:
    pipeline: "0"
    tasks: "4h"
  pipelineRef:
    name: mas-masdevops-deploy
  podTemplate:
    securityContext:
      fsGroup: 65532
