kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: pvc-template
  namespace: mariadb
parameters:
  - name: MAS_AIBROKER_STORAGE_CLASS
objects:
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata: 
      name: mariadb-pvc
      namespace: mariadb
    labels:
      app: mariadb-instance
      component: data-science-pipelines
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: "${MAS_AIBROKER_STORAGE_CLASS}"
      resources:
        requests:
          storage: 20Gi
      volumeMode: Filesystem